### ISSUE TITLE
LibreServo is neither Open Source nor Libre

### ISSUE THREAD

**Issue by abetusk** [Luisonson/LibreServo_v2#2]
As of this writing, the description for the LibreServo_v2 GitHub repository description states:

> An Open source controller to convert any servo motor to the best smart servo.

Yet the license in the [README.md](https://github.com/Luisonson/LibreServo_v2/blob/master/README.md) and source files are under a non-commercial Creative Commons license (the "NC" clause in the license).

The "non-commercial" clause makes this project not open source, in the common usage of the term "open source", and makes the project non-libre, in the common usage of the term libre as it relates to "[free software](https://en.wikipedia.org/wiki/Free_software)".

"Open Source" has a generally accepted meaning of being able to use the digital artifacts for commercial purposes. The [OSI](https://opensource.org/osd/) and Wikipedia's entry on [open-source licensing](https://en.wikipedia.org/wiki/Open-source_license) both articulate that commercial re-use is a (generally accepted) requirement of an "open source" license.

Further, the term "Libre" is, in my experience, usually used to further differentiate licensing terms. I use "Libre" to specifically indicate the "freedom" aspect of it, with the term "Libre" specifically chosen to avoid confusion with the multiple meanings of English word "free" as in "gratis" (no cost) versus the intended usage of "free" as in "freedom". I also use "Libre" to additionally differentiate it from the confusion people have with associating "Open Source" as "source available" instead of the accepted usage of "software that respects freedom".

Wikipedia's entry on [free software](https://en.wikipedia.org/wiki/Free_software) has "libre software" as a synonym.

If the intent of the project is to create a libre/free/open source software and hardware server motor controller, could you change the licensing terms, both in the README.md and in the headers of the source files to reflect this intent? For example dropping the non-commercial clause would make this project open source and libre.

If the intent is to keep the non-commercial clause of the license, indications of the project being "open source" should be removed as should the "Libre" in the project name, as it is neither open source nor Libre.

**Comment by Luisonson** [comment]
Hi Abe,
On the one hand I wanted to tell you that I am Spanish, and I use the word "libre" with more meaning than you give it. It had nothing to do with the project being open or not, it was really a mention to the OpenServo project and regardless of the license, the name is not going to be changed.
On the other hand, I have been checking the license and you were right. I have already corrected the license.
Thanks for your interest in the project and if you have any other request, feel free to ask.
